name: Redis flush test
on:
  push:
jobs:
  pressure-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up --wait --detach --quiet-pull
      - name: Set keys in DB 6
        run: |
            docker exec redis redis-cli -n 6 SET RL:toggle SHADOW
            docker exec redis redis-cli -n 6 SET CB:toggle OFF
            docker exec redis sh -c 'for key in $(redis-cli -n 6 KEYS "*"); do echo "$key -> $(redis-cli -n 6 GET "$key")"; done'

      - name: Display keys and values in DB 6
        run: |
            echo "Key-Value pairs in DB 6:"
            docker exec redis sh -c 'for key in $(redis-cli -n 6 KEYS "*"); do echo "$key -> $(redis-cli -n 6 GET "$key")"; done'

      - name: Flush DB 6 and verify
        run: |
            docker exec redis redis-cli -n 6 FLUSHDB
            echo "After flushing, keys in DB 6:"
            docker exec redis redis-cli -n 6 KEYS "*"

      - run: docker compose logs
        if: ${{ always() }}